import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import { Typography } from "@mui/material";
import SmallCard from "../components/SmallCard";
import React from "react";
import MediumCard from "../components/MediumCard";

type Props = {
  popularDestination: {
    img: string;
    location: string;
    distance: string;
  }[];
};
const database_adress =
  "https://airbnb-clone-d2585-default-rtdb.europe-west1.firebasedatabase.app/";

const popularEndPoint = "popular.json";

const Home: NextPage<Props> = ({ popularDestination }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="/styles/tailwind.css" rel="stylesheet" /> */}
      </Head>
      <Header />
      <Banner />
      <main className="max-w-[1100px] m-auto">
        <section className="p-6">
          <Typography component="h2" variant="h4" fontWeight="500" className="">
            Explore Nearby
          </Typography>
          <div className="pt-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {popularDestination.map((item: any, index: any) => (
              <SmallCard
                key={index}
                img={item.img}
                location={item.location}
                distance={item.distance}
              />
            ))}
          </div>
        </section>
        <section className=" p-6">
          <Typography component="h2" variant="h4" fontWeight="500" className="">
            Train Anywhere
          </Typography>
          <div className="flex space-x-4 pt-12 overflow-x-scroll overflow-y-hidden scrollbar-hide pl-2">
            <MediumCard
              img="https://www.theanimedaily.com/wp-content/uploads/2022/08/Blue-Lock-Anime-Release-Date2.webp"
              title="Outdoor getaways"
            />
            <MediumCard
              img="https://www.theanimedaily.com/wp-content/uploads/2022/08/Blue-Lock-Anime-Release-Date2.webp"
              title="Outdoor getaways"
            />
            <MediumCard
              img="https://www.theanimedaily.com/wp-content/uploads/2022/08/Blue-Lock-Anime-Release-Date2.webp"
              title="Outdoor getaways"
            />
            <MediumCard
              img="https://www.theanimedaily.com/wp-content/uploads/2022/08/Blue-Lock-Anime-Release-Date2.webp"
              title="Outdoor getaways"
            />
            <MediumCard
              img="https://www.theanimedaily.com/wp-content/uploads/2022/08/Blue-Lock-Anime-Release-Date2.webp"
              title="Outdoor getaways"
            />
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const popularDestination = await fetch(database_adress + popularEndPoint)
    .then((res) => res.json())
    .then((data) => data);

  return {
    props: {
      popularDestination,
    },
  };
}
