import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import { Typography } from "@mui/material";
import SmallCard from "../components/SmallCard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="/styles/tailwind.css" rel="stylesheet" /> */}
      </Head>
      <Header />
      <Banner />
      <section className="max-w-[800px] m-auto p-6">
        <Typography component="h2" variant="h4" fontWeight="500" className="">
          Explore Nearby
        </Typography>
        <SmallCard
          image="https://www.theanimedaily.com/wp-content/uploads/2022/08/Blue-Lock-Anime-Release-Date2.webp"
          city="London"
          duration="45-minutes drive"
        />
        <SmallCard
          image="https://www.theanimedaily.com/wp-content/uploads/2022/08/Blue-Lock-Anime-Release-Date2.webp"
          city="London"
          duration="45-minutes drive"
        />
        <SmallCard
          image="https://www.theanimedaily.com/wp-content/uploads/2022/08/Blue-Lock-Anime-Release-Date2.webp"
          city="London"
          duration="45-minutes drive"
        />
        <SmallCard
          image="https://www.theanimedaily.com/wp-content/uploads/2022/08/Blue-Lock-Anime-Release-Date2.webp"
          city="London"
          duration="45-minutes drive"
        />
      </section>
    </>
  );
};

export default Home;

export async function getStaticProps() {}
